version: '2'

services:
  app:
     build:
       context: ./app
       dockerfile: Dockerfile
     expose:
       - "8000"
     command: gunicorn app:app -b 0.0.0.0:8000 --name app --log-level=debug --log-file=-

  nginx:
     restart: always
     build:
       context: ./nginx
       dockerfile: Dockerfile
     ports:
       - "80:80"
     links:
       - app
